move hook logic to management script

diff --git a/sm b/sm
--- a/sm
+++ b/sm
@@ -16,13 +16,13 @@ set -o pipefail
 
 # Error handler
 on_err() {
-	echo ">> ERROR: $?"
-	FN=0
-	for LN in "${BASH_LINENO[@]}"; do
-		[ "${FUNCNAME[$FN]}" = "main" ] && break
-		echo ">> ${BASH_SOURCE[$FN]} $LN ${FUNCNAME[$FN]}"
-		FN=$(( FN + 1 ))
-	done
+    echo ">> ERROR: $?"
+    FN=0
+    for LN in "${BASH_LINENO[@]}"; do
+        [ "${FUNCNAME[$FN]}" = "main" ] && break
+        echo ">> ${BASH_SOURCE[$FN]} $LN ${FUNCNAME[$FN]}"
+        FN=$(( FN + 1 ))
+    done
 }
 trap on_err ERR
 
@@ -42,6 +42,7 @@ CMD="$(readlink -f $0)"
 [ "$BUILD" ]   ||  BUILD=0
 [ "$SERVE" ]   ||  SERVE=0
 [ "$SHTDN" ]   ||  SHTDN=0
+[ "$PUBLISH" ] ||  PUBLISH=0
 [ "$DATEFORM" ]||  DATEFORM="%F %T(%Z)"
 [ "$OUTPUT" ]  ||  OUTPUT="/tmp/sm.log" # useful for catching errors
 
@@ -54,70 +55,121 @@ die() { err "EXIT: $1" && [ "$2" ] && [ "$2" -ge 0 ] && exit "$2" || exit 1; }
 
 # Show help function to be used below
 show_help() {
-	awk 'NR>1{print} /^(###|$)/{exit}' "$CMD"
-	echo "USAGE: $(basename "$CMD") [options] [command]"
-	echo "OPTS:"
-	MSG=$( sed -n '/^for arg in/,/-?/p' "$CMD" | head -n -1 | sed -e 's/^[[:space:]]*/  /' -e 's/|/, /' -e 's/)//' | grep '^  -')
-	EMSG=$(eval "echo \"$MSG\"")
-	echo "$EMSG"
-	echo "CMDS:"
-	MSG=$( sed -n '/^for arg in/,/-?/p' "$CMD" | head -n -1 | sed -e 's/^[[:space:]]*/  /' | grep '^  [a-z|]\+) ' | sed -e 's/|/, /'  -e 's/)//' )
-	EMSG=$(eval "echo \"$MSG\"")
-	echo "$EMSG"
+    awk 'NR>1{print} /^(###|$)/{exit}' "$CMD"
+    echo "USAGE: $(basename "$CMD") [options] [command]"
+    echo "OPTS:"
+    MSG=$( sed -n '/^for arg in/,/-?/p' "$CMD" | head -n -1 | sed -e 's/^[[:space:]]*/  /' -e 's/|/, /' -e 's/)//' | grep '^  -')
+    EMSG=$(eval "echo \"$MSG\"")
+    echo "$EMSG"
+    echo "CMDS:"
+    MSG=$( sed -n '/^for arg in/,/-?/p' "$CMD" | head -n -1 | sed -e 's/^[[:space:]]*/  /' | grep '^  [a-z|]\+) ' | sed -e 's/|/, /'  -e 's/)//' )
+    EMSG=$(eval "echo \"$MSG\"")
+    echo "$EMSG"
 }
 
 # Options and arguments
 ###############################################################################
 for arg in "$@"; do case "$arg" in
-	-h|--help)           # Show this help message
-		show_help; exit 0; ;;
-	-x|--debug)          # Enable debugging messages (implies verbose)
-		DEBUG=$(( DEBUG + 1 )) && VERBOSE="$DEBUG" && DATEFORM='%a %b %d, %r (%Z %:::z)' && out "# INFO: Running in Debug mode"; ;;
-	-v|--verbose)        # Enable verbose messages
-		VERBOSE=$(( VERBOSE + 1 )) && DATEFORM='%a %b %d, %r (%Z %:::z)' && out "# INFO: Running in Verbose mode"; ;;
-	-q|--quiet)          # limit output to major steps and errors
-		QUIET=$(( QUIET + 1 )) && exec >$OUTPUT && OUTPUT=$(tty) && out "# INFO: Running in Quiet mode"; ;;
-	b|build)             # clean and build site
-		BUILD=$(( BUILD + 1 )) && vrb "# INFO: Build will be executed"; ;;
-	s|serve)             # build and serve site locally
-		SERVE=$(( SERVE + 1 )) && vrb "# INFO: Server will be started"; ;;
-	k|shutdown)          # kill local jekyll if running
-		SHTDN=$(( SHTDN + 1 )) && vrb "# INFO: Server will be shutdown"; ;;
-	-?)                   # handle invalid options
-		die "# ERROR: Invalid option supplied: '$arg'. Execute '$(basename $CMD)' -h for usage information"; ;;
-	help)                # build and serve site locally
-		show_help; exit 0; ;;
-	*)                   # handle invalid commands
-		die "# ERROR: Invalid command supplied: '$arg'. Execute '$(basename $CMD)' -h for usage information"; ;;
+    -h|--help)           # Show this help message
+        show_help; exit 0; ;;
+    -x|--debug)          # Enable debugging messages (implies verbose)
+        DEBUG=$(( DEBUG + 1 )) && VERBOSE="$DEBUG" && DATEFORM='%a %b %d, %r (%Z %:::z)' && out "# INFO: Running in Debug mode"; ;;
+    -v|--verbose)        # Enable verbose messages
+        VERBOSE=$(( VERBOSE + 1 )) && DATEFORM='%a %b %d, %r (%Z %:::z)' && out "# INFO: Running in Verbose mode"; ;;
+    -q|--quiet)          # limit output to major steps and errors
+        QUIET=$(( QUIET + 1 )) && exec >$OUTPUT && OUTPUT=$(tty) && out "# INFO: Running in Quiet mode"; ;;
+    b|build)             # clean and build site
+        BUILD=$(( BUILD + 1 )) && vrb "# INFO: Build will be executed"; ;;
+    s|serve)             # build and serve site locally
+        SERVE=$(( SERVE + 1 )) && vrb "# INFO: Server will be started"; ;;
+    k|shutdown)          # kill local jekyll if running
+        SHTDN=$(( SHTDN + 1 )) && vrb "# INFO: Server will be shutdown"; ;;
+    p|publish)           # kill local jekyll if running
+        PUBLISH=$(( PUBLISH + 1 )) && vrb "# INFO: Server will be shutdown"; ;;
+    -?)                   # handle invalid options
+        die "# ERROR: Invalid option supplied: '$arg'. Execute '$(basename $CMD)' -h for usage information"; ;;
+    help)                # build and serve site locally
+        show_help; exit 0; ;;
+    *)                   # handle invalid commands
+        die "# ERROR: Invalid command supplied: '$arg'. Execute '$(basename $CMD)' -h for usage information"; ;;
 esac; done
 
 # Program execution
 ###############################################################################
 
+build() {
+    out "# INFO: Initiating build"
+    vrb "# INFO: Cleaning"
+    bundle exec jekyll clean
+    vrb "# INFO: Updating bundles"
+    bundle update
+    vrb "# INFO: Executing build"
+    bundle exec jekyll build
+}
+
 # don't start debugging until after inputs are parsed
 [ "$DEBUG" ]  &&  set -x
 
+# Clean, update, build site
 if [ $BUILD -gt 0 ]; then
-	out "# INFO: Initiating build"
-	vrb "# INFO: Cleaning"
-	bundle exec jekyll clean
-	vrb "# INFO: Updating bundles"
-	bundle update
-	vrb "# INFO: Executing build"
-	bundle exec jekyll build
+    build
 fi
 
+# Start development server
 if [ $SERVE -gt 0 ]; then
-	out "# INFO: Serving"
-	bundle exec jekyll serve --drafts &
+    out "# INFO: Serving"
+    bundle exec jekyll serve --drafts &
 fi
 
+# Shutdown development server
 if [ $SHTDN -gt 0 ]; then
-	out "# INFO: Killing server"
-	SVR_PID=$(pgrep -a ruby | grep jekyll | awk '{ print $1 }') || err '# WARN: Server PID not found. Likely server is not running'
-	if [ $SVR_PID ]; then
-		vrb "# INFO: found Server PID '$SVR_PID', attempting to shutdown"
-		kill -15 $SVR_PID
-	fi
+    out "# INFO: Killing server"
+    SVR_PID=$(pgrep -a ruby | grep jekyll | awk '{ print $1 }') || err '# WARN: Server PID not found. Likely server is not running'
+    if [ $SVR_PID ]; then
+        vrb "# INFO: found Server PID '$SVR_PID', attempting to shutdown"
+        kill -15 $SVR_PID
+    fi
 fi
 
+# Publish if master branch
+if [ $PUBLISH -gt 0 ]; then
+    # Set the name of the folder that will be created in the parent
+    # folder of your repo folder, and which will temporarily
+    # hold the generated content.
+    TEMP_FOLDER="_gh-pages-temp"
+    MASTER_BRANCH="main"
+    DEPLOY_BRANCH="gh-pages"
+
+    vrb "# INFO: Checking git branch"
+    if [ "$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)" == $MASTER_BRANCH ]; then
+        vrb "# INFO: Storing the last commit message from $MASTER_BRANCH"
+        LAST_MSG=$(git show -s --format=%s $MASTER_BRANCH)
+        vrb "# INFO: Last commit message from $MASTER_BRANCH: $LAST_MSG"
+
+        vrb "# INFO: Starting production build"
+        JEKYLL_ENV=production build
+
+        vrb "# INFO: Moving site to temp"
+        mv _site ../${TEMP_FOLDER}
+
+        vrb "# INFO: Checking out $DEPLOY_BRANCH"
+        git checkout $DEPLOY_BRANCH
+        vrb "# INFO: Removing contents"
+        rm -rf *
+
+        vrb "# INFO: Copying the site content"
+        cp -r ../${TEMP_FOLDER}/* .
+        rm -rf ../${TEMP_FOLDER}
+
+        out "# INFO: Commiting to $DEPLOY_BRANCH"
+        git add -A
+        git commit -m "Built \`$LAST_MSG\`"
+        git push
+
+        vrb "# INFO: Returning to the master branch"
+        git checkout $MASTER_BRANCH
+    else
+        err "Not $MASTER_BRANCH branch. Skipping build"
+    fi
+
+fi
